spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.116.128:3306/jdbc
    driver-class-name: com.mysql.cj.jdbc.Driver

  # 执行sql
  sql:
    init:
      mode: always
      #platform: all
      data-locations:
        - classpath*:department.sql

